// Self-host the web fonts so no request ever reaches Google (a privacy promise
// we make explicit on the Privacy page). Fetches the exact same Google Fonts
// CSS the site used, downloads every referenced woff2 into src/assets/fonts/,
// and writes src/fonts.css with the src URLs rewritten to the local copies.
// Run: node scripts/fetch-fonts.mjs
import { writeFileSync, mkdirSync } from 'node:fs'

// Same families/weights the <link> requested. Chrome UA => modern woff2.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap'
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

mkdirSync('src/assets/fonts', { recursive: true })

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text())

// Split into @font-face blocks, each preceded by a /* subset */ comment.
const blocks = css.split('@font-face').slice(1)
let out = '/* Auto-generated by scripts/fetch-fonts.mjs — self-hosted fonts (no Google request). */\n'
let subset = 'latin'
let count = 0
const slug = (s) => s.toLowerCase().replace(/["\s]+/g, '-').replace(/[^a-z0-9-]/g, '')

// The subset comment sits *before* each block's split; recover it from the tail
// of the preceding chunk.
const commentBefore = css.match(/\/\*\s*([\w-]+)\s*\*\//g) || []

for (let i = 0; i < blocks.length; i++) {
  const b = blocks[i]
  const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font'
  const weight = (b.match(/font-weight:\s*([\d ]+)/) || [])[1]?.trim().replace(/\s+/g, '-') || '400'
  const style = (b.match(/font-style:\s*(\w+)/) || [])[1] || 'normal'
  subset = (commentBefore[i] || '/* latin */').replace(/[/*\s]/g, '') || 'latin'
  const url = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1]
  if (!url) continue
  const name = `${slug(fam)}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`
  const buf = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()))
  writeFileSync(`src/assets/fonts/${name}`, buf)
  count++
  out += '@font-face' + b.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('./assets/fonts/${name}')`)
}

writeFileSync('src/fonts.css', out)
console.log(`downloaded ${count} woff2 files -> src/assets/fonts/, wrote src/fonts.css`)
