// Fetch a high-quality, correctly-attributed city photo per country from
// Wikipedia (the curated lead image) + its Wikimedia Commons licence, download
// a ~1200px copy into src/assets/cities/<code>.jpg, and record attribution in
// src/data/cityCredits.js. Only permissive licences (CC BY / CC BY-SA / PD /
// CC0) are accepted, and every image is credited in-app + on the Sources page.
// Countries with no usable image fall back to the generated skyline.
// Run: node scripts/fetch-cities.mjs
import { writeFileSync, mkdirSync } from 'node:fs'

const UA = { 'User-Agent': 'PassageHackathon/1.0 (https://github.com/Mangluu/passage; hackathon project)' }

const CITIES = [
  { code: 'us', city: 'New York City' },
  { code: 'br', city: 'Rio de Janeiro' },
  { code: 'de', city: 'Berlin' },
  { code: 'no', city: 'Oslo' },
  { code: 'ke', city: 'Nairobi' },
  { code: 'eg', city: 'Cairo' },
  { code: 'za', city: 'Cape Town' },
  { code: 'cn', city: 'Beijing' },
  { code: 'au', city: 'Sydney' },
  { code: 'uz', city: 'Tashkent' },
]

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const strip = (h) => (h || '').replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()
const OK_LICENCE = /(cc[ -]?by|cc0|public domain|pdm)/i
mkdirSync('src/assets/cities', { recursive: true })

// The real Commons file title (thumbnail URLs put "WIDTHpx-Name" last; the real
// filename is the segment before it).
function fileTitleFrom(url) {
  const parts = url.split('/')
  return decodeURIComponent(url.includes('/thumb/') ? parts[parts.length - 2] : parts[parts.length - 1])
}

async function commonsInfo(fileTitle) {
  // iiurlwidth makes Commons render a valid 1200px thumbnail URL for us.
  const u = `https://commons.wikimedia.org/w/api.php?action=query&format=json&titles=${encodeURIComponent('File:' + fileTitle)}&prop=imageinfo&iiprop=extmetadata|url&iiurlwidth=1200`
  const r = await fetch(u, { headers: UA })
  const j = await r.json()
  const page = j.query && j.query.pages && Object.values(j.query.pages)[0]
  const info = page && page.imageinfo && page.imageinfo[0]
  const md = info && info.extmetadata
  if (!md) return null
  return {
    licence: strip(md.LicenseShortName && md.LicenseShortName.value) || '',
    artist: strip(md.Artist && md.Artist.value) || 'Unknown',
    licenceUrl: (md.LicenseUrl && md.LicenseUrl.value) || '',
    thumburl: info.thumburl || info.url,
  }
}

const credits = {}
for (const { code, city } of CITIES) {
  await sleep(2000)
  try {
    const sr = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(city)}`, { headers: UA })
    const s = await sr.json()
    const orig = s.originalimage && s.originalimage.source
    if (!orig) {
      console.log(`${code} — no lead image (skyline fallback)`)
      continue
    }
    const fileTitle = fileTitleFrom(orig)
    await sleep(900)
    const lic = await commonsInfo(fileTitle)
    if (!lic || !OK_LICENCE.test(lic.licence) || !lic.thumburl) {
      console.log(`${code} — licence "${lic ? lic.licence : '?'}" not permissive, skipping`)
      continue
    }
    const ir = await fetch(lic.thumburl, { headers: UA })
    const ct = ir.headers.get('content-type') || ''
    if (!ir.ok || !ct.startsWith('image')) {
      console.log(`${code} — image download failed (${ir.status})`)
      continue
    }
    const buf = Buffer.from(await ir.arrayBuffer())
    writeFileSync(`src/assets/cities/${code}.jpg`, buf)
    credits[code] = {
      city,
      title: fileTitle.replace(/\.[a-z]+$/i, '').replace(/_/g, ' '),
      artist: lic.artist,
      licence: lic.licence,
      licenceUrl: lic.licenceUrl,
      source: `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(fileTitle)}`,
    }
    console.log(`${code} ✓ ${city} — ${lic.licence} — ${lic.artist.slice(0, 30)} — ${Math.round(buf.length / 1024)}KB`)
  } catch (e) {
    console.log(`${code} FAILED: ${e.message}`)
  }
}

writeFileSync(
  'src/data/cityCredits.js',
  '// Auto-generated by scripts/fetch-cities.mjs — image attributions.\nexport const CITY_CREDITS = ' +
    JSON.stringify(credits, null, 2) +
    '\n',
)
console.log(`\nwrote ${Object.keys(credits).length} images + src/data/cityCredits.js`)
